version: '3.7'

services:
  # SQLite Database
  sqlite-db:
    image: nouchka/sqlite3  # SQLite image to interact with the database
    container_name: sqlite-db-container
    volumes:
      - ./data/Chinook_Sqlite.sqlite:/data/Chinook_Sqlite.sqlite  # Mount your SQLite database file here
    entrypoint: sqlite3 /data/Chinook_Sqlite.sqlite  # Directly run sqlite3 to access the database
    stdin_open: true  # Allow interactive mode
    tty: true  # Allocate pseudo-TTY to keep interactive
    networks:
      - elk-network

  # NiFi for Data Processing
  nifi:
    image: apache/nifi:1.26.0  # Specify the version to match docker run example
    ports:
      - "8443:8443"  # Expose HTTPS port
    networks:
      - elk-network
    volumes:
      - ./nifi-data:/opt/nifi/nifi-current/data  # Persist NiFi data
      - ./shared:/shared  # Mount shared directory as in the docker run example
    environment:
      NIFI_WEB_HTTPS_PORT: 8443  # Use HTTPS
      SINGLE_USER_CREDENTIALS_USERNAME: eceuser  # Set username for single user access
      SINGLE_USER_CREDENTIALS_PASSWORD: ecebigdataproject  # Set password for single user access
    depends_on:
      - sqlite-db
    restart: always  # Restart NiFi container on failure

  # Elasticsearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    environment:
      - discovery.type=single-node
    networks:
      - elk-network
    ports:
      - "9200:9200"

  # Kibana for Visualization
  kibana:
    image: docker.elastic.co/kibana/kibana:8.10.2
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
      - elk-network
    ports:
      - "5601:5601"

networks:
  elk-network:
    driver: bridge
